name: accounting_desktop

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5

  google_fonts: ^6.1.0
  flutter_bloc: ^9.1.1
  flutter_lints: ^5.0.0
  injectable_generator:
  build_runner: ^2.10.5
  lean_builder: ^0.1.6
  pdf: ^3.10.8
  printing: ^5.11.1
  injectable: ^2.7.1+4
  shared_preferences: ^2.5.4
  font_awesome_flutter: ^11.0.0

flutter:
  uses-material-design: true



  assets:
    - assets/fonts/Cairo-Regular.ttf