name: accounting_desktop

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5

  google_fonts: ^6.1.0
  lean_builder: ^0.1.6
  pdf: ^3.10.8
  printing: ^5.11.1
  injectable: ^2.7.1+4
  shared_preferences: ^2.5.4
  font_awesome_flutter: ^11.0.0
  hive_flutter: ^1.1.0
  sqflite: ^2.4.3
  drift: ^2.34.0
  sqlite3_flutter_libs: ^0.6.0+eol
  path_provider: ^2.1.6
  path: ^1.9.1
  supabase_flutter: ^2.16.0
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.5
  drift_dev: ^2.34.0
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true



  assets:
    - assets/fonts/Cairo-Regular.ttf